"""add role of user

Revision ID: 338d643b4973
Revises: ca273dc85ad3
Create Date: 2023-11-09 16:05:34.084654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "338d643b4973"
down_revision: Union[str, None] = "ca273dc85ad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "moderator", "user", name="role"),
            nullable=True,
            default="user",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
